package absensiguru.view;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import absensiguru.dao.GuruDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import absensiguru.model.GuruModel;
import java.io.File; // Java IO
import java.io.FileOutputStream;

import com.itextpdf.text.Document; // iText PDF
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.Image;
import com.itextpdf.text.Element;

import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.BaseFont;

import absensiguru.dao.QRGenerator; // ZXing QR Generator
import com.itextpdf.text.BaseColor;

/**
 *
 * @author HP
 */
public class DataGuru extends javax.swing.JPanel {

    GuruDao dao = new GuruDao();
    String jk;
    int idGuruTerpilih;

    /**
     * Creates new form Dashboard
     */
    public DataGuru() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
        resetForm();
        loadData();

    }

    // Method untuk menampilkan data ke tabel
    private void loadData() {//perbaiki
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");

        try {
            GuruDao gd = new GuruDao(); // class DAO kamu
            ResultSet result = gd.TampilGuru(); // panggil method untuk ambil data guru

            while (result.next()) {
                // Ubah kode jenis kelamin L/P menjadi teks agar lebih mudah dibaca
                jk = result.getString("jenis_kelamin");
                if ("L".equalsIgnoreCase(jk)) {
                    jk = "Laki-Laki";
                } else if ("P".equalsIgnoreCase(jk)) {
                    jk = "Perempuan";
                } else {
                    jk = "-";
                }

                model.addRow(new Object[]{
                    result.getInt("id_guru"),
                    result.getString("nip"),
                    result.getString("nama"),
                    jk,
                    result.getString("alamat")
                });
            }

            tbDataGuru.setModel(model);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data: " + e.getMessage());
        }
    }

    private void resetForm() {
        fNip.setText("");
        fNama.setText("");
        fAlamat.setText("");
        cbJeniskel.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barAtas = new javax.swing.JPanel();
        lbDataGuru = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        lbNip = new javax.swing.JLabel();
        lbNama = new javax.swing.JLabel();
        lbJenisKel = new javax.swing.JLabel();
        lbAlamat = new javax.swing.JLabel();
        fNama = new javax.swing.JTextField();
        fNip = new javax.swing.JTextField();
        cbJeniskel = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDataGuru = new javax.swing.JTable();
        btnReset = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnGenerateQR = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fAlamat = new javax.swing.JTextArea();
        txtID = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbDataGuru.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        lbDataGuru.setText("Data Guru");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDataGuru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        lbNip.setText("NIP");

        lbNama.setText("Nama");

        lbJenisKel.setText("Jenis Kelamin");

        lbAlamat.setText("Alamat");

        cbJeniskel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));

        tbDataGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataGuruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDataGuru);

        btnReset.setBackground(new java.awt.Color(0, 150, 253));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-reset-20 (1).png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 49, 3));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(252, 152, 52));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-20.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(3, 153, 100));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-20.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnGenerateQR.setBackground(new java.awt.Color(99, 193, 222));
        btnGenerateQR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGenerateQR.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerateQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-qr-20.png"))); // NOI18N
        btnGenerateQR.setText("Generate QR");
        btnGenerateQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerateQRMouseClicked(evt);
            }
        });
        btnGenerateQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateQRActionPerformed(evt);
            }
        });

        fAlamat.setColumns(20);
        fAlamat.setRows(5);
        jScrollPane2.setViewportView(fAlamat);

        txtID.setForeground(new java.awt.Color(242, 242, 242));
        txtID.setText("ID");

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnDasarLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fNama)
                                    .addComponent(fNip, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addComponent(lbJenisKel)
                                    .addComponent(lbNip)
                                    .addComponent(lbAlamat)
                                    .addComponent(lbNama)
                                    .addComponent(cbJeniskel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnGenerateQR)
                                .addGap(18, 18, 18)))
                        .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDasarLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtID)
                .addGap(8, 8, 8)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(lbNip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNip, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fNama, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbJenisKel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJeniskel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAlamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnHapus)
                    .addComponent(btnUbah)
                    .addComponent(btnTambah)
                    .addComponent(btnGenerateQR))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    private void btnGenerateQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateQRActionPerformed
        // TODO add your handling code here:
        try {
            if (idGuruTerpilih == 0) {
                JOptionPane.showMessageDialog(this,
                        "Pilih guru dulu dari tabel!");
                return;
            }

            String nip = fNip.getText();
            String nama = fNama.getText();

            if (nama.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Nama harus diisi!");
                return;
            }

            //Buat Data QR 
            String dataQR = "ID:" + idGuruTerpilih
                    + "|NIP:" + nip
                    + "|NAMA:" + nama;

            //Generate QR PNG 
            String qrPath = "qr_guru/" + idGuruTerpilih + "_" + nama + ".png";
            File qrFolder = new File("qr_guru");
            if (!qrFolder.exists()) {
                qrFolder.mkdir();
            }

            QRGenerator.generateQRCode(dataQR, qrPath);

            //Tentukan Ukuran PDF
            float width = 155.9f;   // 85,60 mm = 242 point // 5.5 cm
            float height = 241.0f;  // 53,98 mm = 153 point // 8.5 cm
            Rectangle ktpSize = new Rectangle(width, height);

            //Load Template Kartu
            Image template = Image.getInstance("src/Image/Template_Presensi2.jpeg");
            template.scaleAbsolute(width, height);
            template.setAbsolutePosition(0f, 0f);

            //Load QR
            Image qr = Image.getInstance(qrPath);
            qr.scaleAbsolute(68, 68);
            qr.setAbsolutePosition(44, 92); 

            //PILIH LOKASI SIMPAN PDF
            JFileChooser chooser = new JFileChooser();
            chooser.setDialogTitle("Simpan Kartu Guru (PDF)");
            chooser.setSelectedFile(new File("QR_guru_" + idGuruTerpilih + "_" + nama + ".pdf"));

            chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
                    "PDF File (*.pdf)", "pdf"));

            int result = chooser.showSaveDialog(this);
            if (result != JFileChooser.APPROVE_OPTION) {
                JOptionPane.showMessageDialog(this, "Penyimpanan dibatalkan.");
                return;
            }

            File fileDipilih = chooser.getSelectedFile();
            String output;

            if (!fileDipilih.getName().toLowerCase().endsWith(".pdf")) {
                output = fileDipilih.getAbsolutePath() + ".pdf";
            } else {
                output = fileDipilih.getAbsolutePath();
            }

            //Buat PDF
            Document doc = new Document(ktpSize);
            PdfWriter writer = PdfWriter.getInstance(doc, new FileOutputStream(output));
            doc.open();

            doc.add(template); // background
            doc.add(qr);       // QR

            PdfContentByte cb = writer.getDirectContent();
            BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA, BaseFont.CP1252,
                    BaseFont.NOT_EMBEDDED);

            cb.beginText();
            cb.setFontAndSize(bf, 11);

            cb.setColorFill(BaseColor.WHITE);

            float yPos = 52;

            cb.showTextAligned(
                    Element.ALIGN_CENTER,
                    nama,
                    width / 2,
                    yPos, // posisi bawah
                    0
            );

            cb.endText();
            doc.close();

            JOptionPane.showMessageDialog(this,
                    "Berhasil membuat QR Guru\nLokasi file:\n" + output);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                    "Gagal: " + e.getMessage());
        }


    }//GEN-LAST:event_btnGenerateQRActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        GuruModel g = new GuruModel();
        g.setNip(fNip.getText());
        g.setNama(fNama.getText());
        g.setJenisKelamin(cbJeniskel.getSelectedItem().toString());
        g.setAlamat(fAlamat.getText());
        GuruDao gd = new GuruDao();
        gd.insert(g);
        loadData();
        resetForm();

    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        GuruModel g = new GuruModel();
        g.setId(idGuruTerpilih);
        g.setNama(fNama.getText());
        g.setJenisKelamin(cbJeniskel.getSelectedItem().toString());
        g.setAlamat(fAlamat.getText());

        dao.update(g);

        loadData();
        resetForm();
        fNip.setEditable(true);


    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        resetForm();
        fNip.setEditable(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        GuruModel g = new GuruModel();
        g.setId(idGuruTerpilih);
        GuruDao gd = new GuruDao();
        gd.delete(g);
        loadData();
        resetForm();
        fNip.setEditable(true);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tbDataGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataGuruMouseClicked
        // TODO add your handling code here:
        int barisYangDipilih = tbDataGuru.rowAtPoint(evt.getPoint());

        if (barisYangDipilih >= 0) {
            idGuruTerpilih = Integer.parseInt(tbDataGuru.getValueAt(barisYangDipilih, 0).toString());
            Object nipObj = tbDataGuru.getValueAt(barisYangDipilih, 1);
            Object namaObj = tbDataGuru.getValueAt(barisYangDipilih, 2);
            Object jkObj = tbDataGuru.getValueAt(barisYangDipilih, 3);
            Object alamatObj = tbDataGuru.getValueAt(barisYangDipilih, 4);

            String NIP = (nipObj != null) ? nipObj.toString() : "";
            String namaGuru = (namaObj != null) ? namaObj.toString() : "";
            String jenisKelamin = (jkObj != null) ? jkObj.toString() : "";
            String alamat = (alamatObj != null) ? alamatObj.toString() : "";

            fNip.setText(NIP);
            fNip.setEditable(false);
            fNama.setText(namaGuru);
            fAlamat.setText(alamat);

            // Tentukan jenis kelamin
            switch (jenisKelamin) {
                case "L":
                case "Laki-Laki":
                    cbJeniskel.setSelectedItem("Laki-Laki");
                    break;
                case "P":
                case "Perempuan":
                    cbJeniskel.setSelectedItem("Perempuan");
                    break;
                default:
                    cbJeniskel.setSelectedItem(null);
                    break;
            }
        }

    }//GEN-LAST:event_tbDataGuruMouseClicked

    private void btnGenerateQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerateQRMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnGenerateQRMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barAtas;
    private javax.swing.JButton btnGenerateQR;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbJeniskel;
    private javax.swing.JTextArea fAlamat;
    private javax.swing.JTextField fNama;
    private javax.swing.JTextField fNip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAlamat;
    private javax.swing.JLabel lbDataGuru;
    private javax.swing.JLabel lbJenisKel;
    private javax.swing.JLabel lbNama;
    private javax.swing.JLabel lbNip;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JTable tbDataGuru;
    private javax.swing.JLabel txtID;
    // End of variables declaration//GEN-END:variables

}
