package absensiguru.view;

import absensiguru.dao.ManajemenDao;
import absensiguru.model.ManajemenModel;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class ManajemenUser extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public ManajemenUser() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
        tampildata();
        reset();

    }

    private void tampildata() {
        String[] kolom = {"Username", "Password"};
        DefaultTableModel model = new DefaultTableModel(null, kolom);
        tblUser.setModel(model);

        ManajemenDao dao = new ManajemenDao();
        List<ManajemenModel> list = dao.getall();

        for (ManajemenModel m : list) {
            Object[] data = {
                m.getusername(),
                m.getpassword()
            };
            model.addRow(data);
        }
        tblUser.setModel(model);
    }

    private void reset() {
        txtID.setText("");
        tfUsername.setText("");
        tfPassword.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReset = new javax.swing.JButton();
        barAtas = new javax.swing.JPanel();
        lbManajemenUser = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        lbUsername = new javax.swing.JLabel();
        lbPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        tbUser = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        txtID = new javax.swing.JLabel();

        btnReset.setBackground(new java.awt.Color(0, 150, 253));
        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-reset-20 (1).png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbManajemenUser.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbManajemenUser.setForeground(new java.awt.Color(255, 255, 255));
        lbManajemenUser.setText("Manajemen User");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbManajemenUser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(477, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbManajemenUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        lbUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbUsername.setText("Username  :");

        lbPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbPassword.setText("Password  :");

        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(3, 153, 100));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-add-20.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(252, 152, 52));
        btnUbah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(255, 255, 255));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-20.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(204, 49, 3));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-20.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset1.setBackground(new java.awt.Color(0, 150, 253));
        btnReset1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReset1.setForeground(new java.awt.Color(255, 255, 255));
        btnReset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-reset-20 (1).png"))); // NOI18N
        btnReset1.setText("Reset");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        tbUser.setViewportView(tblUser);

        txtID.setForeground(new java.awt.Color(242, 242, 242));
        txtID.setText("ID");

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnDasarLayout.createSequentialGroup()
                            .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbUsername)
                                .addComponent(lbPassword))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnDasarLayout.createSequentialGroup()
                                    .addComponent(btnTambah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnUbah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnHapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnReset1))
                                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                    .addComponent(tfUsername))))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(txtID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset1))
                .addGap(18, 18, 18)
                .addComponent(tbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        ManajemenModel m = new ManajemenModel();
        m.setusername(tfUsername.getText());
        m.setpassword(tfPassword.getText());

        ManajemenDao dao = new ManajemenDao();
        dao.insert(m);

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan");
        tampildata();
        reset();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
        int row = tblUser.getSelectedRow();
        if (row != -1) {
            // Mengecek apakah ada baris (row) yang dipilih di tabel. 
            // Jika tidak ada baris yang dipilih, maka nilainya -1, -1 sebagai penanda bahwa tidak ada baris yang sedang dipilih di tabel JTable.
            String usernameLama = tblUser.getValueAt(row, 0).toString(); // ambil username lama dari tabel
            String usernameBaru = tfUsername.getText();
            String passwordBaru = tfPassword.getText();

            ManajemenModel m = new ManajemenModel();
            m.setusername(usernameBaru);
            m.setpassword(passwordBaru);

            ManajemenDao dao = new ManajemenDao();
            dao.update(m, usernameLama);
            tampildata();
            reset();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah terlebih dahulu!");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tblUser.getSelectedRow();
        if (row != -1) {
            String username = tblUser.getValueAt(row, 0).toString(); // kolom 0 = username

            int confirm = JOptionPane.showConfirmDialog(this,
                    "Yakin ingin menghapus user: " + username + " ?",
                    "Konfirmasi Hapus",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                ManajemenModel m = new ManajemenModel();
                m.setusername(username);

                ManajemenDao dao = new ManajemenDao();
                dao.delete(m);

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                tampildata(); // refresh tabel
                reset();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        // TODO add your handling code here:
        int row = tblUser.getSelectedRow();
        tfUsername.setText(tblUser.getValueAt(row, 0).toString());
        tfPassword.setText(tblUser.getValueAt(row, 1).toString());

    }//GEN-LAST:event_tblUserMouseClicked

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barAtas;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel lbManajemenUser;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JScrollPane tbUser;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel txtID;
    // End of variables declaration//GEN-END:variables
}
