package absensiguru.view;

import absensiguru.helper.Koneksi;
import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import absensiguru.dao.RekapAbsensiDao;
//JasperReports
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HP
 */
public class RekapAbsensi extends javax.swing.JPanel {
    public static int statusCari = 0;
    public RekapAbsensi() {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("FlatLaf Error");
        }
        initComponents();
        tampildata();
        loadComboBulan();
        loadComboTahun();
        loadComboGuru();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barAtas = new javax.swing.JPanel();
        lbRekap = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        lbBulan = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        lbTahun = new javax.swing.JLabel();
        cbTahun = new javax.swing.JComboBox<>();
        lbGuru = new javax.swing.JLabel();
        cbGuru = new javax.swing.JComboBox<>();
        tbRekap = new javax.swing.JScrollPane();
        tblRekap = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbRekap.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbRekap.setForeground(new java.awt.Color(255, 255, 255));
        lbRekap.setText("Rekap Absensi");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbRekap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        lbBulan.setText("Bulan :");

        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });

        lbTahun.setText("Tahun :");

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunActionPerformed(evt);
            }
        });

        lbGuru.setText("Guru :");

        cbGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuruActionPerformed(evt);
            }
        });

        tblRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRekap.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblRekapAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbRekap.setViewportView(tblRekap);

        btnCetak.setBackground(new java.awt.Color(0, 150, 253));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-20.png"))); // NOI18N
        btnCetak.setText("Cetak PDF");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(0, 204, 153));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-20.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(lbBulan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTahun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari))
                    .addComponent(btnCetak))
                .addGap(17, 17, 17))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBulan)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTahun)
                    .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGuru)
                    .addComponent(cbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    RekapAbsensiDao dao = new RekapAbsensiDao();
    //
   public void loadComboGuru() {
    cbGuru.removeAllItems();
    cbGuru.addItem("Pilih Guru");

    try (Connection conn = Koneksi.konek();
         PreparedStatement ps = conn.prepareStatement(
             "SELECT id_guru, nama FROM guru ORDER BY nama ASC"
         );
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            cbGuru.addItem(rs.getInt("id_guru") + " - " + rs.getString("nama"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal memuat data guru: " + e.getMessage());
    }
}


    public void loadComboBulan() {
    cbBulan.removeAllItems();
    cbBulan.addItem("Pilih Bulan");

    String[] bulan = {
       "1 - Januari", "2 - Februari", "3 - Maret", "4 - April", "5 - Mei", "6 - Juni",
       "7 - Juli", "8 - Agustus", "9 - September", "10 - Oktober", "11 - November", "12 - Desember"
            
    };

    for (String b : bulan) {
        cbBulan.addItem(b);
    }
}

    public void loadComboTahun() {
    cbTahun.removeAllItems();
    cbTahun.addItem("Pilih Tahun");

    int tahunSekarang = java.time.Year.now().getValue();

    for (int i = tahunSekarang; i >= 2020; i--) {
        cbTahun.addItem(String.valueOf(i));
    }
}

    
    private void tampildata() {
        
        try {
            RekapAbsensiDao dao = new RekapAbsensiDao();
            DefaultTableModel model = dao.loadData();
            tblRekap.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data gagal ditampilkan!");
        
        }     
    }
    private void cbGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuruActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbGuruActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        cetakReport();
    }//GEN-LAST:event_btnCetakActionPerformed
    private void cetakReport() {
        try {
            String path = "src/absensiguru/view/rekap_absensi.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(path);

            //parameter 
            java.util.Map<String, Object> param = new java.util.HashMap<>();
            //parameter filter
            param.put("bulan", cbBulan.getSelectedItem().toString());
            param.put("tahun", cbTahun.getSelectedItem().toString());
            param.put("guru", cbGuru.getSelectedItem().toString());

            Connection con = new Koneksi().konek();

            JasperPrint jp = JasperFillManager.fillReport(jr, param, con);
            JasperViewer.viewReport(jp, false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mencetak laporan : " + e.getMessage());
        }
    }
    private void cbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTahunActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
                                              
    String guruValue = cbGuru.getSelectedItem().toString();
    String bulanValue = cbBulan.getSelectedItem().toString();
    String tahunValue = cbTahun.getSelectedItem().toString();

    int idGuru = 0;
    int bulan = 0;
    int tahun = 0;

    // Ambil ID Guru
    if (!guruValue.equals("Pilih Guru")) {
        idGuru = Integer.parseInt(guruValue.split(" - ")[0]);
    }

    // Ambil Bulan (karena format: "6 - Juni")
    if (!bulanValue.equals("Pilih Bulan")) {
        bulan = Integer.parseInt(bulanValue.split(" - ")[0]);
    }

    // Ambil Tahun
    if (!tahunValue.equals("Pilih Tahun")) {
        tahun = Integer.parseInt(tahunValue);
    }

    // Panggil DAO
    RekapAbsensiDao dao = new RekapAbsensiDao();
    DefaultTableModel model = dao.filterData(idGuru, bulan, tahun);

    // Tampilkan ke tabel
    tblRekap.setModel(model);

    }//GEN-LAST:event_btnCariActionPerformed

    private void tblRekapAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblRekapAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRekapAncestorAdded

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBulanActionPerformed

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barAtas;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JComboBox<String> cbGuru;
    private javax.swing.JComboBox<String> cbTahun;
    private javax.swing.JLabel lbBulan;
    private javax.swing.JLabel lbGuru;
    private javax.swing.JLabel lbRekap;
    private javax.swing.JLabel lbTahun;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JScrollPane tbRekap;
    private javax.swing.JTable tblRekap;
    // End of variables declaration//GEN-END:variables


}
