package sipresdik.view;

import sipresdik.dao.RekapPresensiDao;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class RekapPresensi extends javax.swing.JPanel {

    RekapPresensiDao dao = new RekapPresensiDao();
    private boolean dataSudahDicari = false;

    /**
     * Creates new form Dashboard
     */
    public RekapPresensi() {
        initComponents();
        loadTahun();
        loadGuru();
        loadBulan();
        loadRekap();
        cbBulan.addActionListener(e -> dataSudahDicari = false);
        cbTahun.addActionListener(e -> dataSudahDicari = false);
        cbGuru.addActionListener(e -> dataSudahDicari = false);
    }

    public void loadRekap() {
        String bulan = cbBulan.getSelectedItem().toString();
        String tahun = cbTahun.getSelectedItem().toString();
        String guru = cbGuru.getSelectedItem().toString();
        DefaultTableModel model = dao.getRekap(bulan, tahun, guru);
        tblRekap.setModel(model);
    }

    private void loadBulan() {
        cbBulan.removeAllItems();
        cbBulan.addItem("Semua");
        cbBulan.addItem("Januari");
        cbBulan.addItem("Februari");
        cbBulan.addItem("Maret");
        cbBulan.addItem("April");
        cbBulan.addItem("Mei");
        cbBulan.addItem("Juni");
        cbBulan.addItem("Juli");
        cbBulan.addItem("Agustus");
        cbBulan.addItem("September");
        cbBulan.addItem("Oktober");
        cbBulan.addItem("November");
        cbBulan.addItem("Desember");
    }

    private void loadTahun() {
        RekapPresensiDao dao = new RekapPresensiDao();
        DefaultTableModel modelTahun = dao.getComboTahun();

        cbTahun.removeAllItems();
        cbTahun.addItem("Semua");

        for (int i = 0; i < modelTahun.getRowCount(); i++) {
            cbTahun.addItem(modelTahun.getValueAt(i, 0).toString());
        }
    }

    private void loadGuru() {
        RekapPresensiDao dao = new RekapPresensiDao();
        DefaultTableModel modelGuru = dao.getComboGuru();

        cbGuru.removeAllItems();
        cbGuru.addItem("Semua");

        for (int i = 0; i < modelGuru.getRowCount(); i++) {
            cbGuru.addItem(modelGuru.getValueAt(i, 0).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barAtas = new javax.swing.JPanel();
        lbRekap = new javax.swing.JLabel();
        pnDasar = new javax.swing.JPanel();
        lbBulan = new javax.swing.JLabel();
        cbBulan = new javax.swing.JComboBox<>();
        lbTahun = new javax.swing.JLabel();
        cbTahun = new javax.swing.JComboBox<>();
        lbGuru = new javax.swing.JLabel();
        cbGuru = new javax.swing.JComboBox<>();
        tbRekap = new javax.swing.JScrollPane();
        tblRekap = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        barAtas.setBackground(new java.awt.Color(16, 185, 129));

        lbRekap.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lbRekap.setForeground(new java.awt.Color(255, 255, 255));
        lbRekap.setText("Rekap Presensi");

        javax.swing.GroupLayout barAtasLayout = new javax.swing.GroupLayout(barAtas);
        barAtas.setLayout(barAtasLayout);
        barAtasLayout.setHorizontalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barAtasLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(519, Short.MAX_VALUE))
        );
        barAtasLayout.setVerticalGroup(
            barAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbRekap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(barAtas, java.awt.BorderLayout.PAGE_START);

        lbBulan.setText("Bulan :");

        cbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBulanActionPerformed(evt);
            }
        });

        lbTahun.setText("Tahun :");

        cbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTahunActionPerformed(evt);
            }
        });

        lbGuru.setText("Guru :");

        cbGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGuruActionPerformed(evt);
            }
        });

        tblRekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRekap.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblRekapAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbRekap.setViewportView(tblRekap);

        btnCetak.setBackground(new java.awt.Color(0, 150, 253));
        btnCetak.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(255, 255, 255));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-print-20.png"))); // NOI18N
        btnCetak.setText("Cetak PDF");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(0, 204, 153));
        btnCari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-20.png"))); // NOI18N
        btnCari.setText("Cari");
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnDasarLayout = new javax.swing.GroupLayout(pnDasar);
        pnDasar.setLayout(pnDasarLayout);
        pnDasarLayout.setHorizontalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnDasarLayout.createSequentialGroup()
                        .addComponent(lbBulan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTahun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbGuru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCari))
                    .addComponent(btnCetak))
                .addGap(17, 17, 17))
        );
        pnDasarLayout.setVerticalGroup(
            pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDasarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBulan)
                    .addComponent(cbBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTahun)
                    .addComponent(cbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGuru)
                    .addComponent(cbGuru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbRekap, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        add(pnDasar, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGuruActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbGuruActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:                                                                                 
        String bulan = cbBulan.getSelectedItem().toString();
        String tahun = cbTahun.getSelectedItem().toString();
        String guru = cbGuru.getSelectedItem().toString();

        // 1. WAJIB klik Cari dulu
        if (!dataSudahDicari) {
            JOptionPane.showMessageDialog(null,
                    "Silakan klik tombol 'Cari' terlebih dahulu sebelum mencetak.");
            return;
        }

        // 2. Validasi bulan & tahun
        if (bulan.equals("Semua") || tahun.equals("Semua")) {
            JOptionPane.showMessageDialog(null,
                    "Silakan pilih bulan dan tahun terlebih dahulu.");
            return;
        }
        // 3. Validasi tabel kosong
        if (tblRekap.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null,
                    "Tidak ada data yang bisa dicetak.");
            return;
        }
        // 4. Guru = Semua → penanda cetak semua guru
        if (guru.equals("Semua")) {
            guru = "SEMUA_GURU";
        }
        try {
            RekapPresensiDao dao = new RekapPresensiDao();
            dao.cetakOtomatis(guru, bulan, tahun, tblRekap);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,
                    "Gagal mencetak PDF: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void cbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTahunActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbTahunActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:                                    
        loadRekap();
        dataSudahDicari = true;
    }//GEN-LAST:event_btnCariActionPerformed

    private void tblRekapAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblRekapAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblRekapAncestorAdded

    private void cbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBulanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbBulanActionPerformed

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCariMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barAtas;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnCetak;
    private javax.swing.JComboBox<String> cbBulan;
    private javax.swing.JComboBox<String> cbGuru;
    private javax.swing.JComboBox<String> cbTahun;
    private javax.swing.JLabel lbBulan;
    private javax.swing.JLabel lbGuru;
    private javax.swing.JLabel lbRekap;
    private javax.swing.JLabel lbTahun;
    private javax.swing.JPanel pnDasar;
    private javax.swing.JScrollPane tbRekap;
    private javax.swing.JTable tblRekap;
    // End of variables declaration//GEN-END:variables

}
